apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: pgadmin-secrets
  namespace: db
spec:
  encryptedData:
    password: AgAEMHtuGoMtALiBPXkALT+E2b6GW6YaiMQRZex6fk6owK3n6+kuMlNyQ+GJtDu5EHv/qIiCyNqEBy+SyzfcsZ3N2Z2D+03ASs2ZV3ScpDOWdb7uBkm2xzZjbOa7ZZghXkSlfFEXOtHkzVZrSFIPzRPYmfL2uJAgnCRo3lbkir8E5PC/Ws5vW8wpeHSb9ylr1hDSK9LEvDNyNQgjjbqPBjqm0GQ8UZMIa5BwMBqgUZH+F9YIXwNj1DKlmO9Zt8WN7xniq0sNLU2NjCin/T6cGaJ8sQEmJi5NasBfT1/1gOEac+hwk3ywUJak46A89apc7MMhGRBPJGvtX1RSOmTfPqDh5NO9CWBXJZvgmP0b+69pB8W3cchYVq+xjOKXGSGNVENnDg15bfgkLZIfg+Ke+m1bwgM4tplfyjdfkbvEFhgFDCmJzv93WrgjhS50zdz3TnDPsK1jtKim6BTjTh5/pEpuRzwGKSnUUrs8ekMf2B4R3dkMKKnbGVnDMaTEYmF4QWjHTcLSdiVJAue1Ddai0DRdZFty4FcI6BLhOkeBUjrHfyLws09ReJLmo+HAbOOVoLzpN8ka3JyMgUwCeGbKInNkzknJCiv/8XkpiPfLd2L8KOP+8qSkcnHGXB3zmZChyM5vYny8jyBDbZbFhA+HZbrFbq7JMb1Pl2HFiRqRQt8DqiMnQ8ZUmlzZEMRuDSXIt7Q7zjSW
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: pgadmin-secrets
      namespace: db
    type: Opaque
