helmCharts:
  - name: onechart
    releaseName: flepguessr-cs214
    namespace: pro
    version: 0.70.0
    repo: https://chart.onechart.dev
    valuesInline:
      image:
        repository: androz2091/flepguessr-cs214
        tag: v0.0.5
      ports:
      - svcPort: 80
        name: http
        containerPort: 8080
      resources:
        limits:
          cpu: "6000m"
          memory: "6000Mi"
        requests:
          cpu: "600m"
          memory: "600Mi"

namespace: pro

patches: []
