helmCharts:
  - name: onechart
    releaseName: flepguessr-cs214
    namespace: pro
    version: 0.70.0
    repo: https://chart.onechart.dev
    valuesInline:
      image:
        repository: androz2091/flepguessr-cs214
        tag: v0.0.1
      ports:
      - svcPort: 80
        name: http
        containerPort: 8080
      resources:
        limits:
          cpu: "5000m"
          memory: "5000Mi"
        requests:
          cpu: "500m"
          memory: "500Mi"

namespace: pro

patches: []
