apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  namespace: test
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-ingress-class: traefik
spec:
  rules:
  - host: k8stest.androz2091.fr  # Replace with your domain name
    http:
      paths:
      - path: / # Specify the path
        pathType: Prefix # Specify the pathType
        backend:
          service:
            name: my-app-service
            port:
              number: 8080

  tls:
  - hosts:
    - k8stest.androz2091.fr
    secretName: my-app-ingress-tls
