apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: db
  labels:
    app: postgresql
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp
      port: 5432
      protocol: TCP
      targetPort: postgresql
  selector:
    app: postgresql
