apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: sushiflix
  labels:
    app: sabnzbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:

      # todo ask sylvain shared pvc permissions
      initContainers:
        - command:
          - sh
          - -c
          - chown -R 1000:1000 /data
          image: busybox
          imagePullPolicy: Always
          name: init-container
          resources: {}
          volumeMounts:
            - name: servarr-data-v
              mountPath: /data

      containers:
        - name: sabnzbd
          image: lscr.io/linuxserver/sabnzbd:latest
          imagePullPolicy: IfNotPresent

          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Paris"

          ports:
            - containerPort: 8080
              name: http
              protocol: TCP

          resources: {}

          volumeMounts:
            - name: servarr-data-v
              mountPath: /data
            - name: sabnzbd-config-v
              mountPath: /config

      volumes:
        - name: servarr-data-v
          persistentVolumeClaim:
            claimName: servarr-data-pvc
        - name: sabnzbd-config-v
          persistentVolumeClaim:
            claimName: sabnzbd-config-pvc
