apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: sushiflix
  labels:
    app: sabnzbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
        - name: sabnzbd
          image: lscr.io/linuxserver/sabnzbd:latest
          imagePullPolicy: IfNotPresent
          # command: ["/bin/bash"]
          # args: ["-c", "sleep 999999"]

          # env:
          #   - name: ROCKET_PORT
          #     value: "4000"

          ports:
            - containerPort: 8080
              name: http
              protocol: TCP

          resources: {}

          volumeMounts:
            - name: servarr-data-v
              mountPath: /data
            - name: sabnzbd-config-v
              mountPath: /config

      volumes:
        - name: servarr-data-v
          persistentVolumeClaim:
            claimName: servarr-data-pvc
        - name: sabnzbd-config-v
          persistentVolumeClaim:
            claimName: sabnzbd-config-pvc
