apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-pgbackrest
  namespace: db
  labels:
    app: postgresql-pgbackrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-pgbackrest
  template:
    metadata:
      labels:
        app: postgresql-pgbackrest
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: postgresql-pgbackrest
              topologyKey: kubernetes.io/hostname

      containers:
        - name: postgresql-pgbackrest
          image: androz2091/postgres-pgbackrest:sha-6085b29
          ports:
            - name: postgresql
              containerPort: 5432
          env:
            - name: "PGDATA"
              value: "/var/lib/postgresql/data/pgdata"
            - name: "POSTGRES_USER"
              value: "postgres"
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: postgresql-pgbackrest-secrets
            - name: PG_BACKREST_REPO_LOCAL_PATH
              value: "/var/lib/pgbackrest"
            - name: PG_BACKREST_REPO_LOCAL_RETENTION_FULL
              value: "2"
            - name: PG_BACKREST_REPO_LOCAL_RETENTION_INCR
              value: "7"

            - name: PG_BACKREST_REPO_S3_ENABLED
              value: "false"
            # - name: PG_BACKREST_REPO_S3_TYPE
            #   value: "s3"
            # - name: PG_BACKREST_REPO_S3_BUCKET
            #   value: "my-pgbackrest-bucket"
            # - name: PG_BACKREST_REPO_S3_ENDPOINT
            #   value: ""
            # - name: PG_BACKREST_REPO_S3_REGION
            #   value: ""
            # - name: PG_BACKREST_REPO_S3_KEY
            #   value: "my-access-key"
            # - name: PG_BACKREST_REPO_S3_KEY_SECRET
            #   value: "my-secret-key"
            # - name: PG_BACKREST_REPO_S3_VERIFY_TLS
            #   value: "y"
            # - name: PG_BACKREST_REPO_S3_RETENTION_FULL
            #   value: "2"
            # - name: PG_BACKREST_REPO_S3_RETENTION_INCR
            #   value: "7"
            # - name: PG_BACKREST_REPO_S3_PATH
            #   value: "/backups"

            - name: PG_BACKREST_CRON_INCR_SCHEDULE
              value: "0 0 * * *" # every day at midnight
            - name: PG_BACKREST_CRON_FULL_SCHEDULE
              value: "0 0 * * 0" # every sunday at midnight
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: postgresql-pgbackrest-v
          resources: {}
        #
      volumes:
        - name: postgresql-pgbackrest-v
          persistentVolumeClaim:
            claimName: postgresql-pgbackrest-pvc
