apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-pgbackrest
  namespace: db
  labels:
    app: postgresql-pgbackrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-pgbackrest
  template:
    metadata:
      labels:
        app: postgresql-pgbackrest
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: postgresql-pgbackrest
              topologyKey: kubernetes.io/hostname

      containers:
        - name: postgresql-pgbackrest
          image: androz2091/postgresql-pgbackrest:sha-e3cba35
          ports:
            - name: postgresql
              containerPort: 5432
          envFrom:
            - secretRef:
                name: postgresql-pgbackrest-secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: postgresql-pgbackrest-v
          resources: {}
        #
      volumes:
        - name: postgresql-pgbackrest-v
          persistentVolumeClaim:
            claimName: postgresql-pgbackrest-pvc
