kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pgbackrest-pvc
  namespace: db
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
