apiVersion: apps/v1
kind: Deployment
metadata:
  name: timetaggertest
  namespace: home
  template:
    spec:
      containers:
        - name: timetaggertest
          image: ghcr.io/almarklein/timetagger:v24.07.1-nonroot@sha256:bfbc2d9a8445529c3d3e16c9be7eb670535f6a53c32b668053a91bcfcd7e8f5b
          imagePullPolicy: IfNotPresent
          ports:
            - name: main
              containerPort: 10286
          volumeMounts:
            - name: config
              mountPath: /opt/_timetagger
              readOnly: false
          env:
            - name: "TZ"
              value: "UTC"
            - name: "UMASK"
              value: "0022"
            - name: "UMASK_SET"
              value: "0022"
            - name: "NVIDIA_VISIBLE_DEVICES"
              value: "void"
            - name: "S6_READ_ONLY_ROOT"
              value: "1"
            - name: "TIMETAGGER_BIND"
              value: "0.0.0.0:10286"
            - name: "TIMETAGGR_DATADIR"
              value: "/root/_timetagger"
            - name: "TIMETAGGER_CREDENTIALS"
              valueFrom:
                secretKeyRef:
                  name: timetagger-secret
                  key: TIMETAGGER_CREDENTIALS
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: timetaggertest-config
