apiVersion: apps/v1
kind: Deployment
metadata:
  name: timetagger
  namespace: home
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: timetagger
  template:
    metadata:
      labels:
        app: timetagger
    spec:
      initContainers:
        - command:
          - sh
          - -c
          - chown -R 1000:1000 /opt/_timetagger && ls /opt/_timetagger && df
          image: busybox
          imagePullPolicy: Always
          name: init-container
          resources: {}
          volumeMounts:
            - mountPath: /opt/_timetagger
              name: data

      containers:
        - name: timetagger
          image: ghcr.io/almarklein/timetagger:v24.07.1-nonroot@sha256:bfbc2d9a8445529c3d3e16c9be7eb670535f6a53c32b668053a91bcfcd7e8f5b
          imagePullPolicy: IfNotPresent
          # command: ["/bin/sh"]
          # args: ["-c", "sleep 999999"]

          ports:
            - name: main
              containerPort: 10286
              protocol: TCP

          volumeMounts:
            - name: data
              mountPath: /opt/_timetagger

          env:
            - name: "TIMETAGGER_BIND"
              value: "0.0.0.0:10286"
            - name: "TIMETAGGER_DATADIR"
              value: "/opt/_timetagger"
            - name: "TIMETAGGER_CREDENTIALS"
              valueFrom:
                secretKeyRef:
                  name: timetagger-secret
                  key: TIMETAGGER_CREDENTIALS
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: timetagger-data
