helmCharts:
  - name: timetagger
    includeCRDs: false
    releaseName: timetagger
    namespace: home
    version: 8.2.0
    repo: oci://tccr.io/truecharts
    valuesInline:
      global:
        fallbackDefaults:
          pvcSize: 10Gi
      workload:
        main:
          podSpec:
            containers:
              main:
                env:
                  - name: TIMETAGGER_BIND
                    value: 0.0.0.0:80
                  - name: TIMETAGGER_DATADIR
                    value: /root/_timetagger
                  - name: TIMETAGGER_LOG_LEVEL
                    value: info
                  - name: TIMETAGGER_CREDENTIALS
                    valueFrom:
                      secretKeyRef:
                        name: timetagger-secret
                        key: TIMETAGGER_CREDENTIALS

                #envFrom:
                #  - secretRef:
                #      name: timetagger-secret

resources:
  - sealed-secrets.yaml
  - pvc.yaml

namespace: home
