helmCharts:
  - name: timetagger
    includeCRDs: false
    releaseName: timetagger
    namespace: home
    version: 8.2.0
    repo: oci://tccr.io/truecharts
    valuesInline:
      global:
        fallbackDefaults:
          pvcSize: 10Gi
      workload:
        main:
          podSpec:
            containers:
              main:
                env:
                  TIMETAGGER_BIND: 0.0.0.0:80
                  TIMETAGGER_DATADIR: /root/_timetagger
                  TIMETAGGER_LOG_LEVEL: info
                envFrom:
                  - secretRef:
                      name: timetagger-secret

resources:
  - sealed-secrets.yaml

namespace: home
