helmCharts:
  - name: timetagger
    includeCRDs: false
    releaseName: timetagger
    namespace: home
    version: 24.07.1
    repo: oci://tccr.io/truecharts
    valuesInline:
      workload:
        main:
          podSpec:
            containers:
              main:
                env:
                  - TIMETAGGER_BIND=0.0.0.0:80
                  - TIMETAGGER_DATADIR=/root/_timetagger
                  - TIMETAGGER_LOG_LEVEL=info
                envFrom:
                  - secretRef:
                      name: timetagger-secret
                volumeMounts:
                  - name: timetagger-data
                    mountPath: /root/_timetagger

            volumes:
              - name: timetagger-data
                persistentVolumeClaim:
                  claimName: timetagger-pvc

resources:
  - sealed-secrets.yml
  - pvc.yml

namespace: home
