apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: timetagger-secret
  namespace: home
spec:
  encryptedData:
    TIMETAGGER_CREDENTIALS: AgAgO+FewD3vUVNETib3fg3AzmTyiQCGN608NQ/9lQj1bVu+GOoCtPH/Q1Df9/rLUt3rEnxrKXvPqB3K8Q3UiLunHCU4LgXLMo5TLLPfyM1O24fxyvpQr/2rGUBKXveebSEQIdJhf/dKvBhT9KSDPWTwe5uLwoNJG785kF2jH0DbVgUwefzHOT2dre0bWm0IHluZMqkYePkb7cN+FgNBrq1qf4/+GaFXXCSnkWM+Ht1hGQ3MXE+7uYeJKYw8EiSq0j6sBNKo8+5g1V1XqlgR9qxQZUlG19Ms7NDmP78EitLkrGErucN/j0ujk8SMl4lJCdBYAIG+EK0i5FGTxU/Zdmge7V2+tbCw5EJ+gwyjLSNN/0MwdN6uiPwkDbbU5ujYR00gQWUAhlOHxJVwodCsHKwXovDrx90MRluHP+33qlnJQUv2/kMnMx57kiRSU8hitmbg+dbywWbkB09Hs2zhpQi0E0XIOIfhZRyZHYCodvr29vAVB7ldkafaHAU0MfH5mbwL1eWFgWJzUDLshGlh9FkTj4VmogHFMQ1eEEsuYHhw0ZG+Gm15YqVdjL4Ld0J+NSRO0QWdysz+Vr+NHNV+mHGfJ1Mh1+qTghA9BxCYcIKSY3yIZ4XCWpiFMUhOhFWbLLT9uDgPW5xXopFqzCdaJJ8C7zsTqPBHvVta78xfpJ2AhVN13+FJFi02nb1IVooXUrpwMy6rFRAjAxu40uGCk7ppPTYqLavbqdCoRRtJ3sBTQ18TibDeGbChnQwcQ1Q/ahC+xuZRLpywct3c9pazBpp4q3UiVWDc1vGDMXDoD3tkNFGk3EkWtxUFffawjsLlROOm6DYVdALPRriXzygOvlUJd2N6Zrxy7SYdTwfHQgeeqYxcxBBCyhGGlztsFmRwFkyFHm3wUvFm65ZeZ0e5dEm7P+QFbw7b5/lm7WcIxcQN5OsR5S9IEH9O29ti0svrA6Bh09DZ2E2t1uO0LJvo11AhfLbe8PWjdDNSDill6RFe8d9FxezcMPqNd5pTpmbVaMyyImXIDtd2TJZWocEVuCOwJyRGwQAMCY2ZHBmYUrwqxoQxZFs5kkzlSSvbjee6yxXAciQqqgNaPpV5COXG/a6qVwSpW7efK2ZA+8LOe50qlJh0BlJWz+eQroovKouMtK/X1URHLuZs0PffIS26KlfQ8SvvXJRa7Tz83Aa7IFGK7/e424u9JBbCK3w+gRInMbUc9dyOQny5zEtRwCmBC4Mgaqmk1JpHRIPjFyryZ7kk7dNW1HhmXmuZyiBdGVglb7hNA1AHs9pLsO+0r30C3XN+TRB9DtheWJTWnJ3Iv33WHF2R5kJQER5Q6XOKo3YRYe1x2NRBuawo0ylSWvmtlWwNUqOM8qI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: timetagger-secret
      namespace: home
    type: Opaque
