---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: timetagger-secrets
  namespace: home
spec:
  encryptedData:
    TIMETAGGER_CREDENTIALS: AgAaPpwfeWr57O1f60WOb+Uu6xvD/Q1SKOfLBIjZRIRBDkoVzD2S/WTP3RHBcxE+DNe9sHdYIiOv14IDgH43BN1xGuz/PvzVIciZgDx3gJw/MUhllYI6XXfVjgroomxJkcfy9KCEwi6Q7cNL99HXyOWdXrDP1GyDHwoY+F8YyDbc1Ui2nOoY2dBZdIhrdR1e50wL56kF++BafEBX7pMx3qq2joxXzSDNk3COHuBt+ap9Hmw3OAgjzyfi9+T3g1O9E2vjQwrFcJ5wPj3WI8n5VWI6+msW0IjW4IioQzvLxnkAbUIFSjeyzT6JhxSKw4Nz1rX2x+Up2A83sx0AV5Kmpqcs4XVrIVmBWA0mK0UL4KoYzlRNSLJd93njVj9gUYr9VHQ1y8Nq1x2Q/wA1+3bGqGIj3mF2woF28mlprwyFcXxEnKogpPjwGiAo3ASyJ1FZheJxwgP1Trv8ijGOurDsSOli3zoEaLlD+ubpvHUtwP0SOr/OPnIwCg9/ol+SJ4tmqSz4Ekkgi72IakButVjKw1KoFivR9BbWnQ/jeDGwLio28zBfmyc0s9TiE0+lR+Y4Xmg6Lr275FiZRvKx3eqQIzAbFgLYIUwltrM0t0Vo98PnaSXM6jN7Gj3Vv/FjjbnNSMpC669oT5KoLK4HWlCDdRz94ZOLEDfIa8WsH7PLmmLENq/H6DE0/D1gQhQTA6uLFdMVKPSmzhpo2qra4UqA4qYO28RtPOTfmS35r+9ASSUGej7OWnsFbThims1727HUJCllOH+/ILIYfHTkAGTSdrXmr9MrUe5psMhasbDQzX97+pQlKFgULjsDcywetxOCiifnMmbW75HUpiuTibProvpj1ALX9RugM6gD9Uol0InEeDdf2yxAVgzwMcaBQoPXnQtMrebO1exASgXN8l+fKtcxKpNVUyVSrnMk9fuRTIY6YMPPtQlCY5hpd5ddfyua6w0+HhuenlU+lT6W6LT/
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: timetagger-secrets
      namespace: home
    type: Opaque
