---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: timetagger-secrets
  namespace: home
spec:
  encryptedData:
    TIMETAGGER_CREDENTIALS: AgASn4ihnEnhW102CYBL/gH/+glnitEqGtVDI6ymgVYTyNZ96XAdcyjJ6nBhYp3y6H6eUZcchjgINHpSS35ZGJmiydoMSCE3x5DFgqkL3F6Udi3H1SwVgmn2ezOsrTvtFU4gifP01MhnIeJODfSI2jNRjq82pkjGFVCG++BpxMlE3KOjLmu88SIdyMGDP5Y/NKzXAmtngOcnqhbdqVCRW9vp1ZKaTz3CKuoi/Sn2ShFaNcF0d9JiTeetgMlHIvjhBdbdN1UWqUeJW95dvt1LnaVk9/MY0YTmDHPRQlU3ToJ86w7OQAIQSnkP17A+gGVBJzdfWtixoQuf92iAvZ4PKyepUQYX23Kx0tr6glQ/UlNOfC/7FN8E44uWAeLJZ46VHU6LGSQJLI6XB3Mh2ozckcNNzM+RR5qClyyMWu8XMsDXBMJOR6bk9lIM8OIAYhrU5/q78t1razuilmQb232097Db+pE3ql8eqGQ3pI53dCIdGWvMgc8d93XsnGjIoV9Jv7S8UDe7JAw08ZG4I2X9qbt4F74Q0cxarYRJjCQvlZikdYVhkjTDQGHPiY00zbX6iYyrPrZjI7ALsNjtGLXWQFW7/PLw/M5iLHWFyGM2FsQbK7DIf42VvTzwSL2XdFXBVBotFgbK1gZjgXiCJYQMkNLUuPzCh4NIyk7oFAXZxYeXQpByGIPslrScgruRNKCDfNav/3tjkdN11Fykcatgz8tLdKtitIfZB1XJkHQ/CA7RFCdn49ujHy1jDoL0vP3Dw403ettfqNltxcTBicPwnO0EoeMAlfVNyyJNX7EGHzf3fID48hDFYCqjxDnC3VfICKGieoLW0uEHjHDIgumWv3CWS+HmgfuOERIG0zy/mcysq05pGPqmWw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: timetagger-secrets
      namespace: home
    type: Opaque
