---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: timetagger-secrets
  namespace: home
spec:
  encryptedData:
    TIMETAGGER_CREDENTIALS: AgCj5uXS+YSDHe5nOfeTr7sqQS7iDIBQyZC0f/L+jJKe5YkwmXg498K90JgjitNEuINHIl5OWjcrIz6My3q2CnCMDdkOH5MOHcBmDChNNz+8J0NfJMyFh0+1Bj02Ar3U3K+Zk/KjPMXdN/X1Hc9UGjhAurn0QkE4O5C6/ZbiOS+nq5NvULUJer9m3WzZtDpiTr+reIRx/QHOpvPPbMWZeUlO0RdNCgSn0Ybjnt2dmkdbsteM/BXh3sqAoLE9/Eh99nj6rJ642AS9SYvvEkz5K2dhtt9Cdaz0Ud+SCLzEb2YyYC0iNYVbRA4+e+lzV/ML5UXHxVFvQK72U6fHhmTBQiDRblY8cHAnZcc/QnpNGfFmRApBMOSks42oh4u8pTYdWyIVNr9v9ua+svJB5qSnzDLqROAGJJfUFKfiFARSR6pCC/7I7YDv/qErfuQ5LLTxjl7fmG/9OdMd+59qMhElaw6aRZ060H3b5F4GemRcdZA5wz+aqsA9r0p2BPooOx2uBNk+mBExjHGx7oTyRnvFi8RZafCqenkyOHZQMhrNroLw2D5Su6aH3edtrVFiVCa5fntq4oUOUqXHx2X4E1xA8Mh8Qhq9LDgtkBU/3WzCQbBdF66V0u9rA4L3zgJx8J0DUn+OFifyGutjs/ZDWpl5sR9DBkIqyCHPZvrNm32eHkuK9rxbwrZY1NJaRh/CmKhSMoUYRvnW8Tc9YEX2rxJycHAHzY7XX8neapZj2zw/Bz0gNHNNJ/jPKPg4fmpuqK3p4s9H2SYnY3PdJHeQcLbaeyAAJdKr1mqrJB2muSP55WRuene/uo+PxgI6EaQnMn2mVcAm6viJFD/H5MHXXSHrJ3lPVtsr/rnSm8UpN0dNP0dDPf45n6R5lA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: timetagger-secrets
      namespace: home
    type: Opaque
