---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: timetagger-secrets
  namespace: home
spec:
  encryptedData:
    TIMETAGGER_CREDENTIALS: AgAom4f4ok1ltrbHqpOKwjegyN22FdW0Eva6QZ+zAkw6giOD2EhiH6whD4hcryavzqEdtqvmH0eEMt5HRRqDdzRNaA9Uir61eiY9a7UAMljReJM4ER41QEAzYEd/Rxgxp9lFLFywjWvo1mpzDHqnEk+7Av990UrAUy21RCQgRVOcA/mVBRouyj2aPfWGsMkKF78+4TkEJqsBu/5altN1XTpcIyQHXs+F6Dv37O+Qr9MvMhEQyhJDB1W+jrFDbZZRBl4gmnxJO/Ul9D4teOD0ExwPjpb2wr7b713z4bxWoefM4jqWu5uECRMZMNY2aoMswK3+JhENjGpdANyT23rUECJJTNnjzSe/6k3HbmmrJ+MjJTkdjsNGqN2QyTVGJKo/hElFo8kyDfW+jQjrDjtamVnv8vbs2h+mju5Vu8ryv8EfMBBGFUf2D1gBXYK/ddmWzvGs6ldW5UEaPoAa8g3lBW0BR0HrsviOBxR50DDkjY3WKe9j3Z9mQ0+B1qV5J5gofaFr9EeiO1jCHtfOXZ/HhLs3GRk3eO6u4TYW/GH6TY5ylGDovJeJLJFREPTt9aJETttE7eatxtqUqJH8bxvYE12EQ+L8QBhCd/yKOtsUCWLItRRixw8yDkq47KXdAhrVu92ixBjb7c4bhuZMp376d2WzUXHMnqqx6bc6zeUAxXXfIIIgXjQmlo3dtBhLoe1bbDVm+5540MZQPmmzB4WYj55m97TO8ZedvgMQ69xMg+tCN3JDWLu6MyCwNTvz/E8zHfedTlOBwE5ZdtWS0Lpdd5eFeCQVLGLDOdikULb+6eV7jEX3+0V8DcsO2lrEiz4hAM84MzbqBPQyEiNwEJzieoK0Bx+Edh44ON3/4CPh1HHma34WYVAWnVma8nlgZdTSkCTboRmebuPQmj6vwOhIhqOttsSWlar1b1vvM22V6ZPtqqLZBlMrnj/7vkg+w/LvlM0+GakPzoQlD8MBXOk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: timetagger-secrets
      namespace: home
    type: Opaque
