---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: timetagger-secrets
  namespace: home
spec:
  encryptedData:
    TIMETAGGER_CREDENTIALS: AgCkpneEhC2vmFsndSen31VB5EmExu8oTkdesdF+sdxc8B9t+LGIQ3wAO0jVgkc1JiSU6yrJuX/ju0apr/6uZqUsF+p4SgQiZY6kbUQfv/QgDmR5dlV4M3Wzqp5Gkg3GdcvnMJ2uM1Sc4geg1kp07I7L+4b44Ruf9zDJJuebg1ePQn4cjY27rTSFcyB95Y0ZUfFqiOH7uOCCr+OAyg9OOW2o65iRweGT61e2NY1UxoFAOOquwqLUptrUdotdzjDKcsr6Fu2w6lFc8g3b1fitBlrZMcAQ+oCGhBfx40v1JnNXLN9s4ff4W8ReCbRU/YH/x2gY2M5NvMjTEYRF8lgwumzbXUlmP19SwFKFIkbP+jKvttgk2hOp5yN8BjFq55aSlOUUtugv2ab0ENM+GUPNX864BlJZ0E8oicyEJeNCAw1cJ+4f8BSebrp3mbNVdhsdzECvRlVOBhLC+qFLaxDp3fHAL61VJfoZTJs+OIYE9X4Tp1skCW4K/oCfNo6Wm8cVYqhdTyGq9W+1+ubQjjbv8RcGeHikmLToqswxskPfn+KCqgvGIQ8iZKvDXcaPpcpbbl/REmzLcvYtm5FAdHQINRm4zQag4r6tTDzqkOrspu3Oo1c/lvjYFQ/b2eDHWkrYGwbrKJBlpX4I3YNv2cK6s2JWRJY4ygCI1RxpMgekF34nYujDZOGvC2J38mnnxWQEQxFE+3SXeMFpno7tw+TtswHr9GEbWaYCiobbBAJpie5LPBmip0ixWLmBDZV1mqHEOYyKH+FhsUTev7gppxmzot0CMA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: timetagger-secrets
      namespace: home
    type: Opaque
