---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: timetagger-secrets
  namespace: home
spec:
  encryptedData:
    TIMETAGGER_CREDENTIALS: AgB4XGDFwVX4PjbBny6PD5wRjfvlJdT8fpATPgIW34C3Uec+85vxMioFwnbNjyF2jJ1FAgp/2QaKgkGp0IQD3KDzCm4TwyCRFrqOU8sxj2HKUy3Y9r0oU6KoSYTiKGLzmzANUg2JCvMOYCImKHISli4eDyAQgdpQ4DQsoQpbOfPFUpv8v7eaxT2VR7l3jQFa3InLjnIRq+AZ+wwGVMYxW3FUIP1ZO5FxlxOVw7knWACHeN3RePU91siDCtIKBwz7ysMqxbLbQ6zTCWGCSW7g3qAZIM6AmwyKtn2AwxAt2DYsS3p/ajj22v1/fshz2FsoXsghU4eIzMgOo+FLfNwOF2mMDWlye4mG7Q9y9WmRn+gTFgJ2IjzhtDqTXK4fFp3T2+xfASEJ1RP4cIY+HGnZnmhLAoBPX0vI1dGdWPYJpTmcYJmdtIrBvilIs/wQfmQRmk1ra4u2Xh8utUZdpqpFBQgQ7RZm4Av9BlHavixp3yfwD8As3vGbk5fUPKcrJ7897qM+F0M6QmWCkn0lotoTwlUNpxuV4QULM3jdiuHWnE2c+nC9dxNARsrdbLHY4LAs+73RQXLDAIQFtYJ9H+UVaB0DR8zZEUiEagnwL8CO8frJ9X135+fRPlC2SZpUv0MIO5Zvy2QVa0gw+Wv32ITDGv2rnm7ZDnVH7MNxUM2p0htTaDyzPiuCufGFvPutVoQLaMiHtO7/DxEEHtXtx1ThiDj/+ab0HRMXUzwcPsE2kVUwWgkwNBSxZJx7WMW3LKlUOo9ieYCWLj8f9eLMIdadJcCLoLlFaItBAUyEN3RedDim7zAHnauf9g0neZXj9NJn57p7SnXBf242hf0sPH3fsbjqjMPq7Bz9kgnlBtlGXVfHSTHJMAE4qw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: timetagger-secrets
      namespace: home
    type: Opaque
