apiVersion: v1
kind: Service
metadata:
  name: timetagger
  namespace: home
  labels:
    app: timetagger
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 10286
  selector:
    app: timetagger
