apiVersion: v1
kind: Service
metadata:
  name: timetagger
  namespace: home
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
    - name: main
      port: 10286
      protocol: TCP
      targetPort: 10286
