helmCharts:
  - name: immich
    releaseName: immich
    namespace: home
    version: 0.7.2
    repo: https://immich-app.github.io/immich-charts
    valuesInline:
      immich:
        persistence:
          library:
            existingClaim: immich-library-pvc
      envFrom:
        - secretRef:
            name: immich-secrets

namespace: home

resources:
  - pvc.yaml

patches: []
