helmCharts:
  - name: immich
    releaseName: immich
    namespace: home
    version: 0.7.2
    repo: https://immich-app.github.io/immich-charts
    valuesInline:
      immich:
        persistence:
          library:
            existingClaim: immich-library-pvc
      redis:
        enabled: true
        architecture: standalone
        auth:
          enabled: false

      postgresql:
        enabled: true
        image:
          repository: tensorchord/pgvecto-rs
          tag: pg14-v0.2.0
        global:
          postgresql:
            auth:
              username: immich
              database: immich
              password: immich
        primary:
          initdb:
            scripts:
              create-extensions.sql: |
                CREATE EXTENSION cube;
                CREATE EXTENSION earthdistance;
                CREATE EXTENSION vectors;

namespace: home

resources:
  - pvc.yaml

patches: []
