helmCharts:
  - name: immich
    releaseName: immich
    namespace: home
    version: 0.7.2
    repo: https://immich-app.github.io/immich-charts
    valuesInline:
      immich:
        persistence:
          library:
            existingClaim: immich-library-pvc
      env:
        - name: DB_HOSTNAME
          value: postgresql.db.svc.cluster.local
        - name: DB_USERNAME
          value: postgres
        - name: DB_DATABASE_NAME
          value: immich
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-secrets
              key: DB_PASSWORD
      postgresql:
        enabled: false
      redis:
        enabled: true
        architecture: standalone
        auth:
          enabled: false
      envFrom:
        - secretRef:
            name: immich-secrets

namespace: home

resources:
  - pvc.yaml
  - sealed-secrets.yaml

patches: []
