---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: immich-secrets
  namespace: home
spec:
  encryptedData:
    DB_PASSWORD: AgCJHuUw9FL9D3CKKFWhVG2VGh+HO887VwoQP9cjlZCYZ53NUlt0F5DNFv2gk4EU1ru6nk6QqBSQi5AuTMUKlvuzxhiCSKjA+Pup0Ze68oVyxAkeEWwNtEI/5aR/KDcBSYRPm3fnlcCwO97c+bsqRlmBZsbkBcF6O4EmPI7GO15TR0Y8G+g9c5EOwYR0IF/FYyIuLGYIehmyM22xDRXNNn8JFv1DrmkFpnvWfa4DCfzEMWFs4VN4FESaFMzuWifHBZQtO/IH/+DQdaNy5j61kZovSoZFXI/TP0/2Enpq1fNf7VcPzNETaR36Io4LvR5JCWkKCYdvLcTqiaSVLVM09yM/ztXVX1NOQ9UlVjFlc3rwRT6YDUh2MH9HZocEu36se3c4B460CEbEid2yCcyxHNqZFNFYSCRNSUmqBkl09w4fvVOCBDps7dFkVGeNvVkAeM1NRdPHFEPee0IiIcSnauOycVQDWOQch0sPaBwZZtoCBhjLFEkW/Mkk6E7bHec8RZm2lcqWHZOV7IILvqMEWoeWjBG3WrMXsWJIL0hHiebikQ1ucCYa43xO8t2f6z9+HUb4mgsWcueSrMtfCDdG22o16N5f8LkLosMesgNHTyAL4foiUpyCOP+W3C35oCrCbU7deQzjnfMaOYZaPwS2CpV6CbAaLUImD/rGydJY52onzqD216SChIJnbWd6l/st/0zM8Ks4CJfuBXfnM1W3
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      labels:
        app: immich
      name: immich-secrets
      namespace: home
    type: Opaque
