apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: sushiflix
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          imagePullPolicy: IfNotPresent

          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Paris"

          ports:
            - containerPort: 7878
              name: http
              protocol: TCP

          resources: {}

          volumeMounts:
            - name: servarr-data-v
              mountPath: /data
            - name: radarr-config-v
              mountPath: /config

      volumes:
        - name: servarr-data-v
          persistentVolumeClaim:
            claimName: servarr-data-pvc
        - name: radarr-config-v
          persistentVolumeClaim:
            claimName: radarr-config-pvc
