helmCharts:
  - name: kube-prometheus-stack
    releaseName: kube-prometheus-stack
    namespace: monitoring
    version: 62.3.1
    repo: https://prometheus-community.github.io/helm-charts

namespace: monitoring

patches: []
