helmCharts:
  - name: kube-prometheus-stack
    releaseName: kube-prometheus-stack
    includeCRDs: true
    namespace: monitoring
    version: 62.3.1
    repo: https://prometheus-community.github.io/helm-charts
    valuesInline:
      namespaceOverride: monitoring
      kubeControllerManager:
        enabled: false
      kubeProxy:
        # see https://stackoverflow.com/questions/73031228/getting-kubecontrollermanager-kubeproxy-kubescheduler-down-alert-in-kube-prome
        enabled: false
        service:
          enabled: true
          port: 10249
          targetPort: 10249
      kubeScheduler:
        enabled: false
      alertmanager:
        alertmanagerSpec:
          replicas: 3
        config:
          global:
            resolve_timeout: 5m
          route:
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 3h
            receiver: 'telegram'
            # routes:
            # - match_re:
            #     severity: ^(oncall|critical)$
            #   receiver: telegram-oncall
          receivers:
          - name: 'null'
          - name: telegram
            webhook_configs:
            - url: 'http://alertgram.monitoring.svc.cluster.local:8080/alerts'
              send_resolved: true
            # - name: telegram-oncall
            #   webhook_configs:
            #   - url: 'http://alertgram:8080/alerts?chat-id=-1001111111111'

namespace: monitoring

patches: []
