kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: workflows
  namespace: argocd
spec:
  sourceRepos:
    - "*"
  destinations:
  - server: https://kubernetes.default.svc
    namespace: "workflows"
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceBlacklist: []
---
apiVersion: v1
kind: Namespace
metadata:
  name: workflows
  labels:
    name: workflows
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workflows-cluster-manifests
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/Androz2091/k8s-infrastructure.git
      revision: HEAD
      directories:
      - path: cluster-manifests/workflows/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      workflowsject: "workflows"
      source:
        repoURL: https://github.com/Androz2091/k8s-infrastructure.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: workflows
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
