apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  labels:
    app: filebrowser
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: filebrowser
  type: ClusterIP
