apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: h5ai-servarr-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 250Mi
