---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: h5ai-servarr-secrets
  namespace: sushiflix
spec:
  encryptedData:
    HTPASSWD_PW: AgBPMcj6djOt775/kWGHDOUmmFb2uOt9/ogUP4xzh+vjoHUAqAGoN5IQa9dowOderGX2pfeXmGzt18v7AJHf4+LXo5TIG7Xnun1H8757pe8sdJLcHQALO+L5y1tAQgRdDcs4QlHePLy2jyqmoGkpxjyDS6mTu8YpwbZr/KwGi1IuGKME/FtBrPydBgRZJdVfWg8TWQ5l884yHm7pl4PZnMeDuYxsigPoH4BWP8pJiJtJh0Fq9ZwDCj5vmfwThVFL+INj9uLIjTjhS5I0biANGgpPXbD8v/bKyAc3Jtr4ew2zzRsczxgwjDKKC0tMcnTuUeu91he3GjOwAA+DTJi6BPhf4axBbuzqJteg+bIjXD3Qj7+0YmwpXfXp9AZ4ozIqp8iH3j7IQ7TvRcnsN5Vr+Ysc9Il1knrEhERR5I8WiSJm/5KiV58S1ys/juJ0JW2aKtcMf0DWLdpb4GnisFqatpbNCGg3FB1gR8YLML5WaDMSmVnqP8QMOLrzYMQdlj8jvhgPNQGtQB0vtWKqz/uoZCCYP/L5NfcfBdhcbQDD0muTqsQ2TzVgpcedJIweDC7i2oauSBNqyBmPICk7FXqs5+Kux/B1v7H/TwydO/CnOmJ23VN8vSL5fpoNpxlH/YXDzShlUDRZHeWU2vDIDrbwWF0EzfV0P1eNx5k8fpldaCHenH6cZQNZvuCWYJYBaocJv/HBObkemkUaQsKDxKT+YqOpW/KtW1VO
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: h5ai-servarr-secrets
      namespace: sushiflix
    type: Opaque
