apiVersion: v1
kind: Service
metadata:
  name: h5ai-servarr
  labels:
    app: h5ai-servarr
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: h5ai-servarr
  type: ClusterIP
