apiVersion: v1
kind: Service
metadata:
  name: stirling-pdf
  labels:
    app: stirling-pdf
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: stirling-pdf
  type: ClusterIP
