apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-data-config
  namespace: longhorn-system
spec:
  cron: "5 * * * *"
  task: "backup"
  groups:
  - default
  retain: 2
  concurrency: 2
