kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: loki-data-pvc
  namespace: monitoring
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
