---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: loki-secrets
  namespace: monitoring
spec:
  encryptedData:
    bucketAccessKeyId: AgCLpaWwWI7hiSdxEmlWyjIvkaOAXMkNEk5QfDLrlniCiqcl8CNrDCfMJvunM4rdRH8RL+9tIupeXRk5zYMZdyUnZMI8aVlhskwrIHPfAI06xPVfJekrIpv2+u48VOlvcY6JAV6A+n1YnRIYM+e1x/FkjErtDSoLaWob1esQBzJsmph8UTgGCUUlplelJmsGPVFz6qy0W1x3a3+7pQI6ZTN6d1LA3vM13qF8Y7sUKHPTellpue+fABWMGUWGbT9EDGpJRMdC/iu68RNaFsgv8AX4I4e9/dG1QIQvjT3x4O/UZsJ00bcn2FSKgs+1eO90FSvkJZQ+hatPM5fmIMWO4fuoINZShX7l04aaT1ZMCBx649wtI+uQDlw3a0GWST1m4RIAJqywGtN/+1P2BrO+gsTKMwGKjZQHMbtTK/P3UwqItwvHiB89j61OhoHiic217s9RCeCnyJMVDio+RgDS6jZtGFPWzQihZJ/ZWMkVj4dBBA49G+4tg71XCXQzMFMOCaazufzLoRKsBe4x+eNwnH34oSC2Y8zgMnsdxfJa1MAS/9r97oEfIeOKu640oZvAhYIvu0jJHt4LkZHUq+DT6dgBFCjmVQAqmiYgeFLUpzREPNjCRA2r3SVD9aTHzSaskAZVJGy8d/h2etJ3kXo4lPoYidufWfrWsvk2ObygEd8nrQvYrc5vY24zinhTolQtrgWMF4katapld/aBq6msrmHBfZB/klms6uuERR4HYTWJkg==
    bucketAccessKeySecret: AgBybJ9hMYoldscOpWHRdX0lIJJCGHBs2rzALSINFSXgvlUMRePpsDtV6NwsYrwsIW6pjSra9duGEPKDPk3eyZIQPmaMuriPey5N/aeYDZOvE3LvZv8i/q0o4Wcyj17pzFnn22hnZk890X7D6K3Jv0mC09m2tyv13IOH5Sg3wesI0seMn1r382bYzFh6nIooVXp+Qi5LBE2D0QhXQG5hr2KHx/1ZBSQxsG4j6vWtz8AreKS/deLKhyC5GlxTbaFDAswa23Qi/JakEEbeUh24R1exJPUWcC95WIE/pXMCgSPZuQQ1escWr7ZNZciMlvTBKhpHOathHtDzT2VLxNebTidC5zGz0CqLoGT8Iqw6RtdoqeJdtSJhitek0fWC5IlMgBwR0eSdtYSf+rjkuMEvXVcoaPqAF9nJPtPSCWHRdhPOvAwgx9HBuIbG3SPytRrU9kUsJ0nTHyFup7Xqo79nNzkVR1m16XsCM7DGXMKyUG7UhK8XLoHGpIDcsSG4/tUwU7MklczXVZY/uwNg9xFATpok+75hxrV1/hRO3Bee9QAVMrH0xaFY5LFFu514e9ahHQqwcq+mqP1AjAwLlCDTuAYJxq+t61J6uVz7zBaJPI/f8ArYj22Vpeq8xxMwY/Mj45BfIj6EJKizjd62wtwIAKsGmIo3qy9Kp76GZyBSXbPm64zuem6WQ7q5tIU5nOhFQqQ8WgkoUSZJbbn0EM9iQVwV99GM80fy8QasCAYy16s82w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      labels:
        app: loki
      name: loki-secrets
      namespace: monitoring
    type: Opaque
