---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: loki-secrets
  namespace: monitoring
spec:
  encryptedData:
    bucketAccessKeyId: AgB2wWiJcpkvd84OjLohyvLCaM+d2+FAJloiJBqsuDcSj3g6RNogPBe6NGT+Jb3FlZCd/Sl5Nh5zjxH4qbVeXL0tyoHxRSjJr/IwTlDA150RsqlGytr3CJgS3PtLdj3QzooswCSQc6pmVMM5try/kv3Cm2gZZT6mQouhcsENSYW8OUzvdjBNZihQjVwcqjleR8zj4ShYvKjJOLKlLAyyRu5PpNH/OJA7UZZprZGvY7jAUR1DrQ0QJIlNC5bOkl5Aj2kkIj1Tym5gObiMraiv/BOSvxx+7nokbsOQmwPB50eN05e+vZcYmOkRuCT8P602Ex2s7TXsU/qSeDfEPUN5h9dWgkqQVkXT2JOPOhMUqIwrt0KSVbR8HyhgEWVszrRK2cgZuRhDQgZX9HR1R09ioIckooVzm+GFnoea14ly5+YnuC/+dBFwUX02qqp9+hXpfWsZZhWa1BEQ/JK3mzkxNXPRz/r8jwJZnCTB8EOoMXjGBHdT5ukG+xoPDqAe37IkNpaSHNaL0bt2Lv/CgjwZWGvAQyYoYFLAChZZxUTACnCY1Hvs9ppZnh31A3+r98RNHQCSVH6acHpMFYSTQlaw+Njyz5vDhAMS4ulsl6hPjMSi1UCfcrRzFrS6o7oNqoOjPRjq3pdCXi0w1mIa+eKj/WTitmAQLGJBgdADPivCMNh/blwSVLmuaAJSehN5KjjbFZzs0QagL5mBuILkiV3CM8IdTwuKHtjBBUuxE9S6VaFQQA==
    bucketAccessKeySecret: AgBdHnn48ZH5z9Tb3Kd9G6dJj916rGceVi5Sps0q2+XF/3krj20NDisQydasY+7nOzFGw2osXYVeJ5jpADtI/BrSMqUNK/fgqmv00SkpG8yRnDAEHisQAc3/3hl4CgGH/4BpCVoWIdAm638km/51Tkm3wUQ0lpA3Hft8DZabNMESo1+ho/yNZF1h4LcgFOenptYFKnwYMtFrjF6imtYASIDtSaEyhv7mxEtu+xj6P6eXG4SeJFIsQAMww8bYvvDb6g9uRP90e+WpxX5Qn+a+MS7KWFeGy61q/RL+qhixvh8dSwZ8W9KMmNu3kfPTM8vf7rpQWHYP3u2wY/QlMu0BxmDv7YtUWygxpjSOdtt0Zr+NWgNrpmjLKmeC03qGj5qrTNH47Y9iZ7UAAap10EbiIqG8B/S1sqT4fTWDwhNJplVpSoTbWEr6vFrxdyLznOhHlTuF9zxfBFsoyFfCOUXujlAOcakJ4FZntUctAI+cIn2zj1c8L2H2jlB+gvHCLrBMYSdOhD7ru/GaoZvclSYoEoF29T30dW2mvzpEvkyWyDHQbalzG1oZg92uHTbNrPi7d2fWevRHj4xkn4uunekFaBTjatykXNN10C7v8kv/furhT23YJUn+gHgipeJcSXFrPyVSTin2qdf0qXw9SmVbLtwy9E9S0i51u6aFv0DIAbRh3Hbl2E+YpmmRZB3rEK/cbKaWrPbLf7W6MFfGh9cTSQ2k4bqd7yrZoh4LvyX46mfkdA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      labels:
        app: loki
      name: loki-secrets
      namespace: monitoring
    type: Opaque
