---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: loki-secrets
  namespace: monitoring
spec:
  encryptedData:
    bucketAccessKeyId: AgCjJLhH6pa/Vu5ZTLNrcvNCJrQcvK/MNSAVGEtgcjFIWpUnwZtLXYfAQFv6TXnfdbrnyFE5iVWpOXLEJs00MZU36tacVNro92kDY5ING+cENQyW7Fju1h+RTtKWJoftIdJMAVSq+o/x9U7+XvsK8+0ezPy74rtmEGRN+pd5IgkJnV9g6nlenTS7qDJO7iJumHx/+/PDEtjJDaK6uHdqLMDuI3ThdTBY2vsQE1uv73zlr1M0VZCld5SyG+Bq/mEuje8Ozc5NDQ23fAQnSswyWH2V32R6WLVLJQK2aJaXtn1uo4yjN/BQFis41DoU0pAxsVEQMULe/lBEGX8pL505EWbTQAtSrQGXZzzZgQFfkc7dICdk7ilY564aRH2kDDTYIrTDeLwfa+IM2zLHBydqC+uWn/JInhTZTHrnG8/tLbqQD2M/+kg54AeA19wGUeD8F6pbVu8UUZJAYE0N0GzLcuKjeUb3jdBroi2Ui6EUgYA9N4k1k5rlNvHZUDt7TNhPuSSipi/NZRnkXNGd+8xDcVkIn1syeB/iaZ0DGq1ZONvmyVCI/OJN9FWjYxNoL8fZlmxxIfZI/HGLj6pv6mADsGOP0eMqSiIMq41TIyhacs233+T0+W/AkTqrc1egX8GAgGYSQEvLKldUJ51EtofruHvQ5XQDe+n1BpseAQfzLgvazIch++sL0IgK4j+EdvA5SPVaP0qYSN6eoygkVIIpkEEN8HAigzSZCE+POO87kAG1ww==
    bucketAccessKeySecret: AgAEZDyhd6IBmhIC4Vso6HaWjjaIOgrEngFT9Ctg96wc8v3jQ3AXdTdqLBhZ3jnINrJi5G48q17EumU/DA84070KQjsSfdWAw33Pv/sHgnulfjpPq0C9dGejh5ZEST9SUg7Kimzmg2ObYMa+vVRM8WhF0LOzJG5/M4Y69sCBkh9H6ZyAN88XHU0yIrGGZDDYoYSKq0hflFKs1ktaqngLqELxJvw2GFWAG7tUKI3NpwkotW0K0+OMzFZaOCqdWku/GrGmcoFyr6SUvDh8QQOi/Kec9oZKOD91xNN5JWDnDItze5RPdnFvEJMngeg4t5R+4GFM8gc3lw5hTGheXYoNNLcq8S85gokccbuvniw55uCiq1X8ooXQNkE/TFBVOrI7KO0tE1M2j+BxhsZPh5891srT1p8/CyH/Q/ASLjrbfKk/QY60anwIDbLNuSpnx4Q/VbV6K55DUJCmQI6N6An3BTjquaEauVPaw3YNaz+Osijivnilx7yjDfItm6aOVUQ4d0Sn94PoNgc8Lk8j5GnhgWFx3cW0oBDV9CCQu8hc8RVitgpYXHA82te4YmbO6vHP3RIll7oETAwA1iAJZvJYBH8nKPz5VhvF+fDyl1/CIM7vUlYCZDAZLRWHcH2k+9OVTGKpu5Ae/NiLpbAqvbiZrah/NA2xKJwJ10+hG0KfgFTZ0wFH//QJPXQ5D1looVuicTQUL/YQSVsd3Y2FGN+pOZ6G0RO3zJgkIUrgYQuC5g5K9w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      labels:
        app: loki
      name: loki-secrets
      namespace: monitoring
    type: Opaque
