apiVersion: apps/v1
kind: Deployment
metadata:
  name: haste-server
  namespace: pro
  labels:
    app: haste-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haste-server
  template:
    metadata:
      labels:
        app: haste-server
    spec:
      containers:
        - name: haste-server
          image: androz2091/haste-server:sha-288b88e
          imagePullPolicy: IfNotPresent
          # command: ["/bin/bash"]
          # args: ["-c", "sleep 999999"]

          env:
            - name: STORAGE_TYPE
              value: "postgres"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: haste-server-secrets
                  key: DATABASE_URL

          ports:
            - containerPort: 7777
              name: http
              protocol: TCP

          resources: {}
