helmCharts:
  - name: onechart
    releaseName: what-is-life-discord-bot
    namespace: managed
    version: 0.70.0
    repo: https://chart.onechart.dev
    valuesInline:
      image:
        repository: harbor.androz2091.fr/fiverr-discord-bots/what-is-life
        tag: dc35d45b
      secretName: what-is-life-discord-bot-secrets
      imagePullSecrets:
      - regcred
      resources:
        limits:
          cpu: "2000m"
          memory: "2000Mi"

namespace: managed

resources:
  - sealed-secrets.yaml

patches: []
