helmCharts:
  - name: lapiz-legion-discord-bot
    releaseName: onechart
    namespace: managed
    version: 0.70.0
    repo: https://chart.onechart.dev
    valuesInline:
      image:
        repository: harbor.androz2091.fr/fiverr-discord-bots/lapiz-legion
        tag: 8e348674
      secretName: lapiz-legion-secrets
      ports:
        - name: 3000
          port: 80
      imagePullSecrets:
        - regcred

namespace: managed

patches: []