apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-test
  namespace: db
  labels:
    app: postgresql-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-test
  template:
    metadata:
      labels:
        app: postgresql-test
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: postgresql-test
              topologyKey: kubernetes.io/hostname

      containers:
        - name: postgresql-test
          image: androz2091/postgresql-pgbackrest:sha-497e5b4
          ports:
            - name: postgresql-test
              containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - secretRef:
                name: postgresql-test-secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: postgresql-test-v
          resources: {}
        #
      volumes:
        - name: postgresql-test-v
          persistentVolumeClaim:
            claimName: postgresql-test-pvc
