kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-test-pvc
  namespace: db
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
