apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertgram
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertgram
  template:
    metadata:
      labels:
        app: alertgram
    spec:
      containers:
        - name: alertgram
          image: slok/alertgram:v0.3.2
          envFrom:
            - secretRef:
                name: alertgram-secrets
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /status
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 20m
              memory: 40Mi
