---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alertgram
  namespace: monitoring
spec:
  encryptedData:
    ALERTGRAM_TELEGRAM_API_TOKEN: AgBA7sTX1RDxDf0xBuPXZFn/S4oPl7K3KpoqSGqvFz2FCTbU2jRSwYB1UiwDEqhCQZ/i2OCHSNGUqzdvM2uHyOaYRPNKDS+Aw2AHNdMu16t4Gzr0fuNrq5RGXebTiVl3D1zbUyJFFT/s/uOSfquuVlC0CTeqaJyeMxlIS15eGBHMIv4xayCKd0Yj76y8qa+PNsDWTYpGuOviXIRs85ADQZTNtbYTx2bihM57PYoNSK5+xHexox77RoSr8y4SsqWUTfbd5NDqMybzMLpU+U7nzeu+Nvxoc5YJzYm6UPgfdW1HM/54FXq2/3ek07EhdVpp0wXfJh0gsatjjaFPHQPjQb8/1tBx/z3n6hpZshB/uh/PVA4bc4bqLsrcRcdXndkABT8hJ3SlKoae+GBv1rdoU6JN7IJrGHDERsJVojkFX9iY37Y0Y73zU4QnNQSPc/0XAxyhuyKkbxjBVqyfAar9n05CP++GHJUBR6Ul5OIu6z+azX1w3WaqRv29Wr9ALjVFfMsXCxmROtjhp1FnH7XWVKxbW/wYrSntcFuokBIAGSR+ERbycbkA8u3XQ2qvTehFwbGy9z1HfqRelNgz1J/8EGrvXX36yYe/tsWTM6CPEkpMltzYfxFxlLJl4s0zSRGyzzXsTDE3WmyLhWg58ahMBtpeKb423Cwei1u610Z3hQ69sDXGsu9M492LtIm0jn1zmc8Oh/Izxh82VN4ulcYHKF7K+9ghHrvU1l54GVuKhdbnn6ByWHe9RefcWoVqoIY0
    ALERTGRAM_TELEGRAM_CHAT_ID: AgAxAMDdb4b7+CrWdCDrmapKyZNuZsot0iBaqrh5LqF6Yc3HwhthJRKRsEVICnM6UVxEdxmtkXj8GZ7DS4dRVIrKk4IvtuELoLQCQKB6W3LEDbQUR23k+X/SpXAUChUIH+gR7tRFNDlk7MRTs9PZ15zLcQhGteNkTL9P+8DXQLR+FHCD58eDwZMp5DYE0/PevTwKDSzdFpw/fvuCe7LRQu6buUOBqYskI+98C4/yoXrx5b49u70Ld2sRC8W0ukYt4wg6jShxtKiNnxCOKlJGwL5KO2NsRmycjYCHPMW+YZSZPVa7ErIV1NgRdsy9rkUq5peex/OkKuplvGl0SOY0UOIxCJxOgrfmFju+K/dCNwFWoE70F2xNK+wHOzM1DCxOAu6kK1leiStRJBIoX1ag2RFtmhtJcR9EEq/SjrO0TQ6un3JZSYNNGkTSP1sBGJHzEX+likHCo7eX9sQLPX4qpd5HHhogcwk70QN9y+FpoUD/Gf3A7dKQZEhjI1o7jE+CVWYdKmeprfsAzro4F/BCF79zfExPP1TOGX7/sN0KTsangYupzCYdHHQ1d2laFSmWYcItUVR0OhDZjU6P9sNBMZK/CyFnsy00WdVIonx7Jnm+S/w6TfAaaP2GQSVbp5YadTIAiSXTLfNCGABBgeUBTCcttTHVzCwkIZ3ALzf7VtlRP3JmSCou7m7JHBwV//H2jF95p0akwT6ZZoZ3/So3kw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      labels:
        app: alertgram
      name: alertgram
      namespace: monitoring
    type: Opaque
