helmCharts:
  - name: onechart
    releaseName: forward-wh-discord-bot
    namespace: managed
    version: 0.70.0
    repo: https://chart.onechart.dev
    valuesInline:
      image:
        repository: androz2091/forward-wh-discord-bot
        tag: sha-e1e6521
      sealedFileSecrets:
      - name: config
        path: /opt/app/
        filesToMount:
          - name: config.json
            source: AgBZHdgdvBgC5PNtCZI0TDd88hWo+rwd2PpUOuC2ULXdn+wqR3+II9UWiFScw159rFif8jhpctwnzMcpBQjnpjv3aQohUmdacdVwVVS1LdrpBnNeNQDzt4rgvdzDWDJJOlPIqe1CGCf3R84lwRxNqMOBHsudvsjkGrlYugbyjpX35byX/mt/RhFm3xWrH5TVLQ9IbeNRPBFwTJjoWPDbWz43Dq4cbnIBVXI3DPCEAXiQkn6O/U5I+k+3q+a8qDQnTcKkhkMvGU865aTiTdNoHqh8/aQM/3/MaNu/eD9bN74VVOAbjxzW252mxue/P/BTxEnuxedhFTf4SsTGPIxYflj+aNz6SeOsU+wj+Ssjj56kcUCvS1cBhracczBEGawwSjdyLASwUz9CoL0E85zttZR1zKHlUABLS+KI2z7hw1P8z58Xh9wYbdpVc4MbbmQl/1NDbi8nj3YMoG/nhQFmQkFMK/2G0Vw7Se6tyMJPTESdHPGJZO+EJEn/TrvU30JsmyYE6usLdcAYGIS5WsuT8DGewuYkuSq/ejzfaTyYlltieE6TlCDyPgRDUmcDiumy+tnLJ0b5QNqMeAslFvstoqTp/aOefJJIoxEbG6HhoXdEM4t5o4400szdkLikbFCKekmmgYVn8UNeUmAQZu2EGb3ViLmfjBnu4423C6oLMBBCKUiAD8ror3bfVvMMeFTQXfuFzp1Zwz/BFeY/WJrz9/BXQ+JizJgsYKL63ajLtrojIoLeLzDZFnwlf5mWbvmcWAWet0xMlgqCBb7DRZ6rNUeFlV41Xot1hbud4c8eL9ES+3u3nw7qHIMTyb2G/+nfhWjXYBvPZsH2GvO/+x/bfLoo3qWn3DQiih/7sbX2Sdmm0VWRiBOfkualk67A94qmkk6gkz5vwVYkDo34Iwm0Bzi7PvG0VyTyX3f5l/gJl7WwAlokR6iPi1/Fp4V16OKRIqm1fWfC5FT7Fxi6z82WTLSTJZO5TR6A8UAJ8I8WCMz1iw7S1kcqKlRuYNEpdHmjN2WNuca2peaCnF/Wri67NwIrWquf8URxzak9vlJknUify81TKoUx/gvCW8Sfh4Cpod9V0TrUlvAQ/cfgpDvvXKuE2PM52sa5wvrUxCbFr1vHQWmMkuliCp+28lsECAsxY5umzaScZ2YzDFwpVDohFGPVn78/gJOprVQxOuXspgaYFD0KIC/wEAFXBmuStAvAQ0ltunVCbPLRR7A0IlHFnVnu0sEaqo4cNP8CrN8Zrk5/eCgPqz6iMZtoFUirRBNDhqIpCjjI9E5CnC9KbYlcGUgNluQgDT0Puq+OjqWHr8bs6hXzXws0miqsX2vkF/hZ/I8Am8yX7zUF+9G3xEKTQDIZhvhKw+EC9RBs+0TH1RcMorQWJBCp3sofR4+1H0z1zeJQeDVvhwEBTX4MiphEJ7qeHkn8RDCQqeuW/pKKznohvKNSFjemuff4yQqI+Q+RJFKLhv0zJzO82C4WG1GcLVpTGpiJBCeK/fK3PiJb2RxeqC2uSLUWHj823c5WlWVKydKIIezf2H0+f0rLz5LAVkI4eIPPYpjDEUCOVmTGE443kcjwkdKBOEMpfu+t4VYf2uDpSuv5gEglSjnreiFBXcKTu0ZlsSuhf06YKgtYMH5jtxQH8hv6zJkXYdtpAPRhfLGX0iAZwtSvlxsZRis3uOfJkETQ8oK20u+QTDlI/E7JVT7NKi/BFnnh5d/AFtu3/RcdUXvEHIBfcy8pKcDv5nofGor+B+64ybHBbRTsh1BPLjC9FNFuv/h/NT9EzHA3d6Jf6CH7e8A/8OQ4afKLdnw3iuhymJxS3Nzo3mRGmI5mfOEMSDP3qw==
        resources:
        limits:
          cpu: "2000m"
          memory: "2000Mi"

namespace: managed

patches: []
