helmCharts:
  - name: onechart
    releaseName: forward-wh-discord-bot
    namespace: managed
    version: 0.70.0
    repo: https://chart.onechart.dev
    valuesInline:
      image:
        repository: androz2091/forward-wh-discord-bot
        tag: sha-e1e6521
      sealedFileSecrets:
      - name: config
        path: /opt/app/config.json
        subPath: config.json
        filesToMount:
          - name: config.json
            source: AgCciSR1wBm1C6dkkLWU93vt85riVeWrqpQyVZ0XVHatfz7YQJuqYsnVwejVCRxaKrOmQ9w11l2sJLY81yhhJDmdb5Sk3LmvVvtc5T67vwgj9gtifl0L0ni3zqNHWr51I7DPd9IlQ9hsSgmUb9Koj8av/ToKcDB5zOJoOILTJA22MF4OmTHr8fMXEk3jhXA6j6XMtwaos/A9N26CCfZTkHJUWmM08tfnZARn+za6ZVsgLy7iEGjeb11wfF59Wc0QwhY7VO5zm5m8rHZsNxfpuu6FciIcuuolWsqufgFe8JUWzoIimb5vR5X4Pme12uaem8rVvtoGHIsJ4j5e9dpeTHIJ26LrrDeGjfJeHWjPLQm9V2YwEXnkzXV4PtKK2lcgBprgzpXh7KTBHM9N/urd4G1jfnC3b2fA17oGPC4foSTncMOKZy9NGGwRhpVNdeMdo0YJkKHc7e3tpkGxyAYvLsSO2ajPOp6pX00zLUSuRt9d9yroHkAvgWv4K+LfLFnW1dmOYvR2TOV03i78Qacs+LTlbbyEishwTRiVZesh1FqkHliCVFoOKxjWhK+MfXkIfcEF2INipL2UP6fcn05URnDAPbbBNgWamGduBPjsBNiiAuAj1z5AI6N3sGzw7c/HbNsCUwCnNiOsSwib7aF7JmbrvWD5jxb9PXF1mX4k5yTi4P+1f8xS4Ba6E9su1KTtnMYZe0dbGz/bREwwmYllYal7L9rEyx/9YWG4OrR0jBbiUwTDgq5d9tWfkIGSS6Mrqb04xnE+TGDtmAt+HSaUlW+rss17clUug7/SXenymkceofi4zb9wJM0buYlrp+R+fA2AsmCXWNrrXJ5nMru5PWH27Gjyzxi9hLCQXrT2jhTbpcXCS6BhTMDzBhleoFfO3DObOXhA5I/I4ZoLaEZFDrBYU3GwTdE7nR8R9YZvU4vO9lLhhITpwNlMCqfq4yR80q9T1hyNM8zBgD61ySMdaewXG38dPnf4YsW0mIm1fBADdBrMm40REde+c7eGfL3x7n34dIVBLNiB8x2MQRbxfHKsGyBiD9l1QU8Um79U5lxTKgA4WFe+RoL5TbW1TScveIcHoiqSs80Ae7I+RJfv/gcxBNQtYOm6FPQmdRk9GPOaZvXWD1ZXqq5rIsloD2BpIu7U3sgIXDgP0atyBchRt1XpokLg+cxIqYQhF+wysh3BjRvzQBw/7gN+NEhzbnQ6YqoCAFo7rQsbjZ8qJ4s/k8vI8eXc+6Kgcg2mL/dasaRZ9a9vSlHrZ//Ut8H8InOrSodDq6/uT8L0vAltdH09+xb49TiuHEQzrSqMDdJOyi1Ix5fQhNarEB+rnd1xPw6yiWOhtBycEuS9G1w3oIe0Nrh1o0hTQ4X7NTt0pu+pRlXgBOW77QyKwv0sIvUxNRHNcCOUjbdQxodKdxyNt1mMB1E3vs5eFQoB7reyDAPv3B9vdC3otJAk8BFWg5MWsm/PuW2/0uKA/4m416IKfP24NeQKUbgj61hRhs2gNdESVzh7965DwVCZFdpOYaRo1XljkW+j2xjFsoHyy2r0qnLdA4XTD+HG28GsbijKC5QGtikSorK73rCHBvgyuRTsypQkO6mngjBoBIzV/XB6weGG6rJY/4W/NzzZn8tIwPa4YBfdUnn1LNl0VXvZALG0co32dNnSYne6K4PgXAVe50DUnn6McxRzNmj5oXJdWnceQqjs5ne4z8SBbR44w1toHJQTY2EEnYXjGkCgsao9E6fID4tTmdh/NyHuTDkyzUWY0p2Rv+aE67CnsPAasPhE1IP9wS7g3RAw/qAM+9HwfYJK2A0wSHlhiYcwMEbzRToFhWKWCTq2dXXK4FLkirqwuHUgIhGwZzY14OvGbA1OTrZVOdMtxvKxTKwvIHgQaXOuWsWA9pkTjFZLGrGkQl874ef92VMjrvhpBHgUXFTkaPZjnenUY37Vp4qUVQXiBKhhGcUl2OB9XYhaB8IKk0VRILHLmW6MerTPThnFsxpQDhwCYdvp0CcvwedOG60/sbGkj6IASWz7gggQz0Jitv9rrDCoGI8Xv6x+miLn2sNAkVVojYYdFtjoXEgB5sc1aITrw3mWg8W356pwem0bdU69JPt7JNlGQ8px278d8jpZlnJrBg==
        resources:
        limits:
          cpu: "2000m"
          memory: "2000Mi"

namespace: managed

patches: []
