helmCharts:
  - name: onechart
    releaseName: forward-wh-discord-bot
    namespace: managed
    version: 0.70.0
    repo: https://chart.onechart.dev
    valuesInline:
      image:
        repository: androz2091/forward-wh-discord-bot
        tag: sha-e1e6521
      sealedFileSecrets:
      - name: config
        path: /opt/app/
        filesToMount:
          - name: config.json
            source: AgBuhPoXAVakjQvQpASjFlI1pQZUbwdxfWUQT6bn/VyEiUA4jRm8F11kz/e/sbzftVMrWI/nsW65xD0AB/eujmtEzrqlSzZaj5wY5FBwxIp+oDA1vvEtN76s69y/4EjTh+zeVF4GEETP+wI7QKtbfXpUK78Y71NblZX1nuEYAqtH0qwOSkZ6dYPjXES4ZW8V1KhMwYd0v6aSQlUQ+MmNf3Jabxf1Chdj24djoZrAja77gk81XpokwlF22tJoAoz4KuUSMY+WVbGFFIMBb4t9ilXqAQbPxZIIhsOMF8afuX9zOjZBgp3rFTPN2Zb5R7vt/nfrh/FYtVNhQ+eAiPCdXpoOHR5Em4zZmcvKYm8of08DUXQxjB4+sqvVFD+KCYyCU5s3VNQy73p3MjUwUb0mpMebF9ZkMY1G4zG4M5dWC7yMbRhLhS+tlKCwgQVi6BQAfwCeyFzrZV54AtZECUZpit/ZtsOCZBjwScCOGWupnsAw/65bS76vh7aTXAr914jZNIaHU0//xhYWekK2ruFqv+pM/yxfp4gYmmzJnjdw21tj5+59wnhZRz9GRYRFWj59EOFoG6TH0Huk/vJypPhFyfEjn2eLDO6eb02rYxkRUJSODWKlONJxBP+uyBovffAARx786njfyXwFALhsYVpy8hB1kvjirjpf5yzUyGY6DdGg9+K+ndDu9sWL2Ws9RWkZsNH/x3OwiG+L5wmPL0jnEIsf9SkvRT1O60vHIfUU3KBSaoK/eWc95MD0rSANFNfzQLKdQwhdjiDZDjef5XXMyaOOIroMiVifbXxloRtu8bXLOdvZc0R4j9cUX+U+5eSlV2p6mZt7y0366mTzsN2aYaqyjsW50FeTp+s75YDk0LkvLviJLj33mKteUSfWLZTHkHvqs1kbnpbKaK1SaWw0vc7gV/QkBo1KtU4DMRAyY8klaUxcQINYsVkWDZ+xFfJCqJSF38WhiopdWVQJaC4RUcAu2bfLmOLT0RMcwgXS3Uf8s9dWVZhAn3/HnaDXvqfTVh9GnU21OY0AksOWDHGQeMu3wEP97DWUJE9ZERnDqY5xCr5u/Q6XxUZfUiGosPDqMvCsUn8lskrt/jLetx9Hpc1rcTdpE6gViYYY9WOeNYwlOqY4yRj/xR8UuthqTduYBAO369uHdlG2COKb7wQhR8LuH2QOjLrPlW/L5QN/UR7Pff5WCFLRRlHFeK6OXq1KXlhUHiaw/4dL9Z8OBzl+TtNjNLHjNiqvoAUK5xIw3bAEzQb2/uaNpQtMMNBBNLXYjkeMU0Q/8Ni1j8ZjKiH0ezWzxpOK+GCLcte9nJ2HDAMz3+FNObjvd1LePHwiDjZMbHoE7Cq4g8QiM5EbwHppqysQEI3pqNPhgGwaD7AE8O/XBZdp2MsSnF7Nf37xVEwOtftrMDZfs1NWkE3qV99La46tR1Rbcm7ycvetKJ03Qu93+N8QAzF6u6Nzv4BpTZFakpfqlI1VKstnl+mZF5mDUs0EPdGTLXatyP9V6WByrJ60GXJGX2Mdww5e0G5cG5Y3hFz/plc8nmtrMYoBFAdnpBQNqHJLWTSeQsCYehVGlES5XOkaOr8F4pJqI1dXE0ynnclxpoTuJwqci9E74i875tYyz4R1hz88LnP06SmY5l72BfCusnu9SalfEv+JAuY4WjtQb8l4r3rBh0mfwnU2mqtNTdyLkCyBu+sK17gce3chzY5/a7qS5UXXzwhX3gzOjmIsTVRHQmUVp4otKN0s9p5LfWVcdhd+H9m+CqXKMZyRSc5r76oLJtDRNYgqJ07eUP/uUMdDQ3fgB1qYNSVXt0K84Uet8zNJRW0z6SXllarOLxcwaqdanlA9WRlzMu5jqcNyx7sVMjjg8GKmLusq0TuvrEe9otA9BWNTSQpE2MYu4yEq3q3agwJJwijYRw==
      resources:
        limits:
          cpu: "2000m"
          memory: "2000Mi"

namespace: managed

patches: []
