helmCharts:
  - name: onechart
    releaseName: forward-wh-discord-bot
    namespace: managed
    version: 0.70.0
    repo: https://chart.onechart.dev
    valuesInline:
      image:
        repository: androz2091/forward-wh-discord-bot
        tag: sha-e1e6521
      sealedFileSecrets:
      - name: config
        path: /opt/app/
        filesToMount:
          - name: config.json
            source: AgBWsy8UmjgFAlwfxb0Eq6rD/rREOCAH1HDX9FyKbMrNtR3ZqQhgHzlwx0HtFGm/ub/2lpEzNnZuzFhH7YYftNjQ8pCZ2ghv470UrUSgpJk4Ew5QcX+hbHp7MbTVEW72PyrDnHLZj0I5WE7J6aD7JQvCGKKjY7bWqox6FnHZDAV451wpUWZ/SJhVVTgxgBxbW6ol5vlth7faHROjDl8E3CYXzkyiCGLPslIlKhla16lmGOPMVHbLunGIKRxIQB438HkVnV97nC4c3eIAPz+ZP/5f7cqAyO2NSnZhBD674iCysCZxCNyL9Ni0MtpFuqK4p78sUtyBykRbHRkcVqRQ5K+Dip2Kh+iVFbK8HKbnxo9NafwL6TyAoA/rP6tYRlE0zP+1a+8mkfs6YQIdCChxGpjEhuJJgpUaxeD8koO0A6ehg7PYdwRsNkVYN3l+EOCwed6ur9Gqu777+Tcv2qNxtYmFab1KdOuk/VszfeMLsEmpFIdhGbKEevimP5Bc6AUaTHwB+iI/IaprNtSrsRqO8F0iUZJHWdaKGgUxCQutRWqabuvwW/7loa6fTZypbI7vGbNLsZsXWlRGLlB8qbYGS+Nj2J9GuJm09zpPpQapn6yTqAcoiFZ7KbbWxYW3/N5VNqAmKb5X9nfXleusQ2ifYJ2Y8nNaA+kAeAFF+j+zRwkdjbTiKUSckWZ8phCkxQ1X6cxTbLR5cbOqmQata+jjb0I2ACEQsXNjnEXzHdhL2REC6Qh13KHnqTuvUweesfydRyqOF56CRL8P2Nts+99OB0AdNEoPRzZ5bky3U6Sv+CVWlio1vm2KwYFiTgm7re7LDqZv2cf8mh4/cM1wuThsbZ33SohMPG5NTxVrOzq0wDTELoRc1RWC8xizFwvI/xSi8+XYrj+5LZETyuXuxWegRS/QLqcqZbAkXjf2OU+/g+boVRBtT6NBjNQ8XWhTagJsITXn5RI21NtHHfYCspruNN6PCPXm3ZnPlxMYnKlt3mkLzEH/AbhmYKqOospAzfgBKu2/N17arSYUBC9CW2LRZ+eT7Zrl1L+IGRcwUj6BUbJE7HUE+qnIiSuMAxAYNNHF3DD9nDeaVatAiCtWqxikJiuEha8o3hwMxGZg/dqjsNGLmeIItvW7MpytDsTCfQszJgYustqBj9/mhKxIc0ANv7HtAz1p+DabBoPEd0eFogMhjw6ErDsfd4e8cung83z6+PH2VawACX5Vf8vuhHr1uS+Vsk3+x0O2JWHhZNnqOGinfFIERep6orV7mNhS+7t1u24bFH5SF025WTPTzOfDhzZbnkrFpCvV9oXIFgq55LR63lB+l8TMupM3Zv5Er9UzUg1tikkPitl6rvn8HMcmnxJAdKPknVBlIayZyzbE0L9zPUovoeRYLl/Vn1lc0mT+Dtb5k0Z2IJEXqoLToCpO8LnxEnEOKIPP0obQIOxaVDuKI/58XIe7lcvHm3lLvZexU/Wr51phUZApbKq8pRaGM6dDJBF5sXklpomL/yfKfmyHcv3P0UiV/vkycK1ZzQYaTFh3eHmEhIMW3Zs4qt91N6pkob/W4kXOpHdUisMnHT0rgX7yzze5SNkXxunxj2emm+jVXRK7Cuvxq7pnS7bHJYfNeeLmQD0pDVLbzlfEeavdKBWFEd+pvfdI0G1f267gowILF47yzHvXjBBEUm3gBKHbrZKcvTfH/pwnjqRbIh41iJZtx0MANVpR7TqE2St1puh3xUkxComk/1+be+Nff5FHgUZKLxRWDN5YW2LHthSEJdPeMToFTd9XGOwJgGzM1V76HLBHb+SM6aawpaJeSFNFijH4eXaQkAUxyaVcC7lAVYo5+Kycjw==
        resources:
        limits:
          cpu: "2000m"
          memory: "2000Mi"

namespace: managed

patches: []
