---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: forward-wh-discord-bot-secrets
  namespace: default
spec:
  encryptedData:
    config.json: AgCeuvJ0WvGay4szsc0rENDpvS5/G15juOlgJPgalok8qnnicbpjgDiaf6/074KQNG3h8lR3Qssp+1fPKlgp1UtaXVk2ylC4+eFGwkpzwlKyQ4dZFWiZtq8oxpIQ7XPe6aVlqu3TBuyq/2WzPNC8vRoQZQ2hhLg7kMeqb4pePQ5if0by7QuI10olrL15VkusRZE8QP2ASr8rWau3i0A8FpkHP9X/BYbxwZ3yDfKGr1/PdlAusljQS5mn45QIBuNbUMSU32ch2fEszkiQ1ILf8EJ8ZJ9Lo8fUe4TkHPlHGI3kTwk9YAnBm9dYUkdt3VuIpzoRoQBA8Z/YI9Sb9Bg17VShdhgE7AH6YLa0PaG9Vk2QXFbjhTkhRoKOsId7WcSNnjENwLPNx0Zw651BjCu2cmPo5g+98dAoEzjoSdOD05FGFOjPkYT1spztvuPwkDlObWmYJyOyG3AnlkvjKqT36UaD0yQ+EAH4p+UfuI5P/yp80vQIuMp0ffSDmRGZpe58JnM0nr4YnZs691Sctz7R4BJYX1ohqO7zC5vmvEveCV+RKCpDve5IUfI0SCVEgt80d3uQ6NI1i20uUonzqwmexhi3GaiNiS6FOV4VMyg2pcIV3hKhejMVv9eEwHoiGjyTG4YhVmmnlkeByV7cieaOyJPQ3QUW2j3fAG60bxZlHPE2uvJa0VW3ajJebMD0Ic1lss9axXcx1IRr0/IwNwnw1evUiiijImba04AkVv4Lx0A8kNRzKO+DDJssJkYGjTpdPkc0K+r2dU+s4B0BY1kHEO0v0Q6gA/H2Y7GzgAlAXsdO9HX/UK6h9IQtit1S1tu9SVpqq7K83TcwCX/+vXQtlGVzicaB4WhoCgYkecn3FD3gbFdvsfqEYqkpVA2HmJMYQS05J13cS4te03eUf86aZGyLkhYi5VDdaQEUmujFlHPZ2GhOZXqenrq0WvfEf//zgsWs9BgzqCMXtpF1goxuhqVpAZ5nQRAZHVDq0ezytgMhi80GkfmVRPwYN9dXgYZI0+X0IbUtV1lLA8lAniq6k91LvO7C2EVyvk1cjEZRmK2RusPoGFjiyITZSOktjNsW1mlRQj696MH3czP1MNlzpJhOlngYpqQPQd+ibjTXyr2P3RLVsswwi3qIkRcRXuWIkwV8vhljt/HhgC6neAlT3dre4fDCpbBbAmLV/YWc6b7KKRkR0f9SwSb6sB97pgYoAKM3ABJVoY/qQiJD5MxvU+DRAx0W/onGcnmJ5qMq8/Q3uKWLB0ewFcIQpQW4EzJhsSiWF+sEVZ6j/tcGdNZnVMUuIdRuplo6AubpN+tcmwS0T20T5uhG1qnx9aeV+egB7nbrrxiksF4PWeVbtscFBvOSQ2wvOL23g2CKTZELg1tn7VJ2FOFhqWL6uj7e0sSYSylcg8jyNZdcxRm0AhC3coJriR1TPlP1E6Zl3GWaB/g5Ca/aFl1sorGlr3hKMtF45F/t9Oj8z6hThLTZlAp2Nc8QUF9nE+my/19J5ThMgsXOguy6tWRjoF/5Zq/ryEznwTwQhtu1pVmbIO7jAOEKXnynnjsSQnqpJ3PY4hv3fVkqfG58P58qGoFIAR/QeHRtQ0xMGTu0o9p6Sn0nVUh2FqZ21oU13FZOdCDTOturVqibW8bK3tAMOeAllNcCJ8q9mwat6qhnI1IQRaPanN+fLofH7VIbeo1bN49Uvw2dC7vDKEfsxQtCb7OeodVYRUXI2mGl22/n7UssDXj+FNxQ+4XG9U0wAIWqlnYUgwBCS6kHW+k=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: forward-wh-discord-bot-secrets
      namespace: default
    type: Opaque
