---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: forward-wh-discord-bot-secrets
  namespace: default
spec:
  encryptedData:
    config.json: AgAfcADnSEAzQwWCTw18/oBhJR3L9W9Mf6bx9fsXgb0/yn9irOgUAgVWWceg4VjEb0NikvIjvoRikttnI8bEAXPMqIsEw/RHIDIriyxtFXqnWqAznb0nklkp5aGV2k0xBgsKMBG+I1PknzBJ27bX1tClSjHRHM7oeQR+pdx7tQxH8xqYk0WmAcrDUuILbTFEoXZC+GW/J0U853J7o1bPE5YxemBokG79tEXCfmF2ICfb/vkkrtYRd24FcyCPKu0CvIjQXXVTIzSauOYp7ltGMBusnA5HuICxwt0QCcy8CIZzXdRNeI3QoYbEWjA8mvDFmTUbKnzNFbP3MnxsV/f9EnK2tWlYbHe+uTyaSSARbWYedC6jR2cZu16KO90iUDwtSEeCJr9MTMZu6gVd7nQRk68aefqtu3/IDrPHXX0eKz5AKSWGqw78jbfVYV6Tj0oZ7CYAn9H/rW1oDnRz5G6/uEy3X22oJDXr3054i/E5Ula1b9xsaCCAW7YMjcFe9ldvwyHcCRx0BpQMKS5qxfGwFEfVD2nj81txSSAco/mOftQMf7hsERb9m9QyVkIsqOrlK5k7EW5X/MchlEpw+ReXbRD49O4EFjHlT0ewF20Z8qOvnicDC61XT50EUV1mLcn0hJc/AW9ez5kTNDR2pA0MELUn1VWpiYdJVmnYe66YHEvAmT7TLY1eOOT0y2wfDmgxOGFFLsix3MlhTKFkykwYPomVoib71a2FCRXCENK33UjFAtwZkJu6Am/cYEZiGkY4KGFwlSDXrTEic2FO+HcbDMk871nzRASa6uArXUUoq2Ys7eQbmy6cLQtFySGy1OehRIiQcZiB0zwMDRs58wEPUkSB9IGcNmf5rZljBam9N7tQZlAdJWngfQHpi92Lb6TiGPcpmSuNpY3QN0B9uldze9j1W9kh9u+AUoJmpYSPmkAy+wEg/LFwDtAfUAG/9IaxhDuspzynUWXzDf93mYl5P3Icc+kZrtx7oltZrnMQgivvXtBZfRAzvDEcPKoVaJIOC4ehxMp817N00ujxMLXZt84pi/Ci7wDqir93oXSzrfxhza/BVxpCiIZ5mwCYCXSbDx2ODth3zhF0ek1HpA6u6N/tiI/3q36NnoTKXKKnVZla/PT1Hrc2fbO13lIYB/0dVFenQ3BRpngOEeuypv9N3MYJ3yzkef9KlMS5htmngUaltKxw9kvb3Mq1kOWvJZey7HT7EZlmKsixcLku2DyNVJ8ypIM5ePrDgnobHk/vzAhqOgGU5ymTKgvKj8RhQ6mWVjoz1fxCL4oUXFmE3zc+8phR+0/Rh0uknVdv/SJEA2lP97BwOYL9sIvyVt5mP6WXDfIofw7h568PunJiEvIZByH4B8iOWN9gbr7UbQ7P3lnwceUEPtJ8VefCk0FQvynav7yALcUc33zMQ9a1vhJs4DFixMNVCKmvjkjDi5IQB7HWo/bv7HKqbuf8WpWiwI2jrhn2DrC9C5E0z7NgHuLL2rsFBQze/vyhpdltHk65oOVGHr2PQLK4XPvgAXgTWwqRDpej10SYEkjvtlpx8OB8oZ6IOEC+m/f+uI/VomAkDRjTvZtElqaToBZsh5qcwxEbs8qELJm3zrqcGTsxj9TlEqpBoMDClvq/pwR/ItLJdIos9keKAHy1Jiqv/76weJX3mYB5JWCfpAgvhgPKWHAv401z3V1renFF+RRsAS1/2x2f/VxLwCPjZ/Qv92qBwTuQkBjIC+UyxCPpBsJJvhIoE/n0oxSvyHWL4HZ6jldVkiECbRI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: forward-wh-discord-bot-secrets
      namespace: default
    type: Opaque
